### ISSUE TITLE
do_not_clear = True not needed for InputText elements

### ISSUE THREAD

**Issue by PySimpleGUI** [chrisbeardy/Gdirsync#4]
https://github.com/chrisbeardy/Gdirsync/blob/4226693e634f18210764a9c77611ebe5bdfa78e0/src/gdirsync.py#L59

You don't need to specify this on all of your Input Text elements.  The default is True.

Some of the old old examples have that value set, but the newest docs don't.

**Comment by chrisbeardy** [comment]
Thank you for this, I shall change.

**Comment by chrisbeardy** [comment]
implemented
